version: '3.8'

services:
  mysql_db:
    image: mysql:latest
    restart: always
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: 'cars-app'
      MYSQL_ROOT_USER: 'root'
      MYSQL_PASSWORD: 'MyHoney15!'
      MYSQL_ROOT_PASSWORD: 'MyHoney15!'
    ports:
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'

  mongodb:
    image: mongo:latest
    restart: always
    container_name: mongodb
    ports:
      - '27017:27017'    

  rabbitmq_cont:
    image: rabbitmq:latest
    container_name: rabbitmq_cont
    ports:
      - 5673:5672
      - 15673:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_nodejs
  
  microserv_1:
    build:
      dockerfile: cars-microservice-mysql/Dockerfile
      context: .
    depends_on:
      - mysql_db
    ports:
      - '8000:8000'
    env_file:
      # Specify the location of env file :^)
      - cars-microservice-mysql/.env

  microserv_2:
    build: 
      dockerfile: cars-microservice-mongodb/Dockerfile
      context: .
    depends_on:
      - mongodb
    ports:
      - '8001:8001'

  microserv_listener:
    build:
      dockerfile: cars-microservice-mongodb/ListenerDockerfile
      context: .

networks:
  rabbitmq_nodejs:
    driver: bridge

  
  